name: system
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - cryptography=42.0.5
  - expat=2.5.0
  - libffi=3.4.4
  - openssl=3.0.13
  - pip=23.3.1
  - pycparser=2.21
  - pymysql=1.0.2
  - python=3.12.2
  - pyreadline3
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sqlparse=0.4.4
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - asgiref==3.8.1
      - django==4.2
      - django-ranged-response==0.2.0
      - django-simple-captcha==0.6.0
      - mysqlclient==1.4.3
      - pillow==10.3.0
      - windows-curses
prefix: D:\software\python\envs\system

